### ISSUE TITLE
make release information more prominent

### ISSUE THREAD

**Issue by mellybelly** [Phenomics/hpoweb#13]
People are having a hard time finding the releases and the schedule for them. 
It would also be great to have a releases page, with the latest activity autogenerated. Look at what @cmungall does for uberon.org, for example.

**Comment by cmungall** [comment]
I think the issue that we never updated the redirect, has always pointed at svn: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/hp.yml

**Comment by iamkoehler** [comment]
there is no releases repository. also no real schedule at the moment. I can make the switch to github-releases now and extend the website.

**Comment by cmungall** [comment]
Ideally we could retrospectively make gh-releases for older versions from hudson but this may be a lot of work

**Comment by iamkoehler** [comment]
But maybe just for a subset (one per every 4 month) ?

**Comment by iamkoehler** [comment]
but again: switching to github will imply to update the purl after every release, because there is no link to the "latest" GH release.

**Comment by cmungall** [comment]
I always use ONT/releases/YYYY-MM-DD, that way a single redirect does the trick.

see
https://github.com/pato-ontology/pato/blob/master/src/ontology/README-editors.md

**Comment by iamkoehler** [comment]
release is shown on bottom of the page. will keep it there
